[workspace]
members = [".", "crates/smtp-server"]

[package]
name = "smtp-s3-dump"
version = "0.5.3"
edition = "2021"

description = "SMTP server that dumps received mail to S3"
repository = "https://github.com/ibotty/smtp-s3-dump"
license = "GPL-3.0-or-later"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
arc-swap = "1.6.0"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1", default-features = false, features = ["default-https-client", "http-1x", "rt-tokio", "sigv4a"] }
futures = "0.3.28"
mail-parser = "0.11"
mime_guess = "2"
notify = { version = "8", default-features = false }
notify-debouncer-mini = { version = "0.7", default-features = false }
serde_json = "1.0.107"
smtp-server = { path = "crates/smtp-server" }
sqlx = { version = "0.9", features = ["runtime-tokio", "tls-rustls", "postgres"] }
thiserror = "2"
tokio = { version = "1", features = ["tracing", "macros", "rt-multi-thread", "signal", "time"] }
tokio-rustls = "0.26"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "std", "registry", "fmt"] }


[profile.release]
strip = true
