---
name: CI
on:
  workflow_call:
  schedule:
  - cron: '0 0 * * *'
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:

  test:
    name: Check and test
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      with:
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
    - run: sudo apt-get install -y swaks

    - name: Format
      run: cargo fmt --all --check

    - name: Clippy
      run: cargo clippy --locked --workspace --all-targets --all-features -- -D warnings

    - name: Test
      run: cargo test --locked --workspace --all-features

  audit:
    name: Cargo audit
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  zizmor:
    name: Lint workflows
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
      with:
        advanced-security: false
